version: '3'

services:
  jupyter:
    build:
      args:
        - WORKDIR=/workspace
        - PYTHON_VER=${PYTHON_VER:-3.12-slim-bullseye}
      context: ./py3
      dockerfile: Dockerfile
    #restart: always
    entrypoint:
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=5555
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    expose:
      - "5555"
    volumes:
      - ./py3/root_jupyter:/root/.jupyter
      - ./workspace:/workspace
    ports:
      - "${APP_HOST_PORT:-5555}:5555"
